console.log("My first console project")
var first_name = "Sagar";
var last_name = "Singh";
var full_name = first_name.concat(last_name);
console.log(full_name);
var a = 16;
var b = 9;
var add = a + b;
console.log(add);
var c = 25;
var d = 15;
var sub = c - d;
console.log(sub);
var e = 12;
var f = 8;
var multiply = e * f;
console.log(multiply);
var g = 100;
var h = 5;
var divide = 100 / 5;
console.log(divide);